# create-vnet-playbook.yml
---
- name: Create virtual network in Apstra
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_vnet
  environment:
    APSTRA_API_URL: "https://10.87.2.40/api"
    APSTRA_USERNAME: "admin"
    APSTRA_PASSWORD: "Apstramarvis@123"
    APSTRA_VERIFY_CERTIFICATES: 0
