# create-sz-playbook.yml
---
- name: Create security zone in Apstra
  hosts: localhost
  gather_facts: false
  roles:
    - role: lock_blueprint
    - role: k8s_create_security_zone
    - role: unlock_blueprint