# delete-pod-playbook.yml
---
- name: Delete pod in Apstra
  hosts: localhost
  gather_facts: false
  roles:
    - role: lock_blueprint
    - role: k8s_delete_connectivity_template
    - role: unlock_blueprint
