# pod-create-playbook.yml
---
- name: Create connectivity template in Apstra
  hosts: localhost
  gather_facts: false
  roles:
    - role: lock_blueprint
    - role: k8s_create_connectivity_template
    - role: unlock_blueprint