# roles/lock_blueprint/tasks/main.yml
---
- name: Lock the blueprint for security 
  when: event.resource.kind in ["Project", "Namespace"]
  block: 
    - name: Extract blueprint with default and convert to string
      set_fact:
        bluprint_label_value: "{{ (annotations['apstra.juniper.net/vrf'] | regex_search('\"blueprintName\": \"([^\"]+)\"', '\\1') | first) | string }}"

    - name: Connect to Apstra
      junipernetworks.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth

    - name: Get blueprint
      junipernetworks.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
      register: bp

